sudo: required
language: c
compiler:
- gcc
services:
- docker
script:
- travis_wait 20 sleep 600 &
- docker pull $DOCKER_IMAGE:latest
- docker create -v $PWD/firmware_images:/firmware_images --name $DOCKER_CONTAINER
  $DOCKER_IMAGE:latest
- docker cp . $DOCKER_CONTAINER:$BUILD_DIR
- docker start -a  $DOCKER_CONTAINER
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 107.170.221.27\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- mkdir deploy_images
- mkdir deploy_images/ar71xx
- cd $FIRMWARE_DIR
- for f in *.bin ; do cp $f ../../deploy_images/ar71xx/${f%.*}-test.bin; done
- cd ../..
- ls -al $FIRMWARE_DIR 
- rsync -Pavrt deploy_images/ar71xx ${DEPLOY_USERNAME}@107.170.221.27:/var/www/builds.sudomesh.org/public/sudowrt-firmware/latest/.
deploy:
- provider: script
  script: docker commit $DOCKER_CONTAINER $BUILDING; 
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_TAG; 
          docker push $DOCKER_IMAGE:$TRAVIS_TAG
  on:
    tags: true
env:
  global:
  - DOCKER_IMAGE=sudomesh/sudowrt-firmware
  - DOCKER_CONTAINER=sudowrt
  - BUILDING=$DOCKER_IMAGE:$TRAVIS_COMMIT
  - BUILD_DIR=/usr/local/sudowrt-firmware/
  - FIRMWARE_DIR=./firmware_images/ar71xx
before_install:
- openssl aes-256-cbc -K $encrypted_c4a3135f480b_key -iv $encrypted_c4a3135f480b_iv
  -in deploy_key.enc -out ./deploy_key -d
